resolver: nightly-2020-06-25
compiler: ghc-8.10.2
allow-newer: true
packages:
- .

extra-deps:
- smtp-mail-0.3.0.0
- text-format-0.3.2
- Diff-0.3.4
- liquid-fixpoint-0.8.10.2
- liquidhaskell-0.8.10.2
- liquid-base-4.14.1.0
- liquid-ghc-prim-0.6.1
- github: PLSysSec/frankie
  commit: b9ee2c0f7667025d0d0ac3a43ded43d1d1d63c28
- github: storm-framework/storm
  commit: 90ac0528832dea42c3abaa0090bf505ddd223f35 


